[project]
name = "fedora-compose-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ijson>=3.3.0",
    "pytest>=8.3.4",
    "rich>=13.9.4",
    "ruff>=0.9.6",
]
